/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CCreate: typeof import('./src/components/cCreate.vue')['default']
    Create: typeof import('./src/components/Create.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Reg: typeof import('./src/components/Reg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/components/Toast.vue')['default']
    XForm: typeof import('./src/components/xForm.vue')['default']
  }
}
